# Generated by Django 3.0 on 2019-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('unit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unit')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('short_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Information')),
                ('long_info', models.TextField(blank=True, null=True, verbose_name='Long Information')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit', models.PositiveIntegerField(verbose_name='Unit')),
                ('whole_sale_price', models.FloatField(verbose_name='Whole Sale Price')),
                ('customer_price', models.FloatField(verbose_name='Customer Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('short_info', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('contact', models.CharField(max_length=200, verbose_name='Contact')),
            ],
        ),
    ]
